[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
evm_version = 'paris'
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
gas_reports = []
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 1024

[rpc_endpoints]
shape_sepolia = "${SHAPE_SEPOLIA_RPC_URL}"
shape = "${SHAPE_RPC_URL}"
